title: KdbInsideBrains
subtitle: IntelliJ IDEA Plugin for KDB+

url: "https://www.kdbinsidebrains.dev"
email: support@kdbinsidebrains.dev
github_username: kdbinsidebrains
repository: "kdbinsidebrains/site"

logo: "/assets/images/logo.svg"

# I don't know what's below
description: >- # this means to ignore newlines until "baseurl:"
  Open-Source IntelliJ-based IDEA plugin for <a href="https://kx.com/">kdb+</a> time-series realtime database
  with full supporting <a href="https://code.kx.com/q/">KDB+ Q</a> programming language.

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: default

search: true # true, false (default)
search_full_content: true # true, false (default)
#search_provider          : algolia # lunr (default), algolia
#algolia:
#  application_id         : # YOUR_APPLICATION_ID
#  index_name             : minimal_mistakes # YOUR_INDEX_NAME
#  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
#  powered_by             : true # true (default), false
#  files_to_exclude:
#    - _posts/2017-11-28-post-exclude-search.md

# No posts - no atom_feed
atom_feed:
  hide: true

# Reading Files
include:
  - .htaccess
  - _pages
  - _project
  - _features
  - _settings
exclude:
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - config
  - Gemfile
  - LICENSE
  - log
  - README
  - tmp
  - vendor
keep_files:
  - .git
encoding: UTF-8
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

analytics:
  provider: "google"
  google:
    tracking_id: ${{ vars.TRACKING_ID }}

google_site_verification: ${{ vars.SITE_VERIFICATION }}

# Outputting
permalink: /:categories/:title

# Plugins (previously gems:)
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

footer:
  links:
    - label: "Plugin"
      icon: "fa-solid fa-play"
      url: "https://plugins.jetbrains.com/plugin/16746-kdbinsidebrains"

    - label: "Trainings"
      icon: "fa-solid fa-graduation-cap"
      url: "/trainings"

    - label: "GitHub"
      icon: "fa-brands fa-github"
      url: "https://github.com/kdbinsidebrains/plugin"

    - label: "Issue"
      icon: "fa-solid fa-bug"
      url: "https://github.com/kdbinsidebrains/plugin/issues"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo

# Collections
collections:
  project:
    output: true
    permalink: /:collection/:path
  features:
    output: true
    permalink: /:collection/:path
  settings:
    output: true
    permalink: /:collection/:path
  trainings:
    output: true
    permalink: /:collection/:path

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single

  # _project
  - scope:
      path: ""
      type: project
    values:
      layout: single
      sidebar:
        nav: "sidenav"

  # _features
  - scope:
      path: ""
      type: features
    values:
      layout: single
      sidebar:
        nav: "sidenav"

  # _settings
  - scope:
      path: ""
      type: settings
    values:
      layout: single
      sidebar:
        nav: "sidenav"

  # _trainings
  - scope:
      path: ""
      type: trainings
    values:
      layout: single
      sidebar:
        nav: "sidenav"