title: KdbInsideBrains
subtitle: IntelliJ Idea Plugin for KDB+

url: "https://www.kdbinsidebrains.dev"
email: support@kdbinsidebrains.dev
github_username: kdbinsidebrains
repository: "kdbinsidebrains/site"

logo: "/assets/images/logo.svg"

# I don't know what's below
description: >- # this means to ignore newlines until "baseurl:"
  Open-Source IntelliJ-based IDEA plugin for <a href="https://kx.com/">kdb+</a> time-series realtime database
  with full supporting <a href="https://code.kx.com/q/">KDB+ Q</a> programming language.

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: default

search                   : true # true, false (default)
search_full_content      : true # true, false (default)
#search_provider          : algolia # lunr (default), algolia
#algolia:
#  application_id         : # YOUR_APPLICATION_ID
#  index_name             : minimal_mistakes # YOUR_INDEX_NAME
#  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
#  powered_by             : true # true (default), false
#  files_to_exclude:
#    - _posts/2017-11-28-post-exclude-search.md

# No posts - no atom_feed
atom_feed:
  hide: true

# Reading Files
include:
  - .htaccess
  - _pages
  - _project
  - _features
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
encoding: UTF-8
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Outputting
permalink: /:categories/:title

# Plugins (previously gems:)
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kdbinsidebrains/plugin"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo

# Collections
collections:
  project:
    output: true
    permalink: /:collection/:path
  features:
    output: true
    permalink: /:collection/:path

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single

    # _init
  - scope:
      path: ""
      type: project
    values:
      layout: single
      sidebar:
        nav: "project"

  # _features
  - scope:
      path: ""
      type: features
    values:
      layout: single
      sidebar:
        nav: "features"